export const GET_ARTICLES = 'GET_ARTICLES';

export const TOGGLE_HAM = 'TOGGLE_HAM';
export const TOGGLE_IS_DEKSTOP = 'TOGGLE_IS_DEKSTOP';
export const SET_FOUND_ARTICLES = 'SET_FOUND_ARTICLES';
export const TOGGLE_COMMENTS_FORM = 'TOGGLE_COMMENTS_FORM';

export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_ARTICLE = 'ADD_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const LOGOUT = 'LOGOUT';
